services:
  - type: web
    name: dineflow-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_USE_POLLING_FILE_WATCHER
        value: 1
      - key: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
        value: false
      - key: Database__MigrateOnStartup
        value: true
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: CustomerWeb__BaseUrl
        sync: false
      - key: DeepSeek__ApiKey
        sync: false
